import Poster from "./assets/images/Poster.png";
import PosterAvatar from "./assets/images/PosterAvatar.png";

export const movies = [
  {
    id: 0,
    movieType: "Action",
    movieName: "Black Widow",
    poster: Poster,
    posterAvatar: PosterAvatar,
    qoute: "Part of the journey is the end.",
    desc: "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    mark: 8.3,
    type: "Movie",
    releaseDate: "2019-04-24",
    runTime: "181 min",
    genres: "Adventure,  Science Fiction, Action",
  },
  {
    id: 1,
    movieType: "Action",
    movieName: "Shang Chi",
    poster: Poster,
    posterAvatar: PosterAvatar,
    qoute: "Part of the journey is the end.",
    desc: "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    mark: 8.3,
    type: "Movie",
    releaseDate: "2019-04-24",
    runTime: "181 min",
    genres: "Adventure,  Science Fiction, Action",
  },
  {
    id: 2,
    movieType: "Action",
    movieName: "Loki",
    poster: Poster,
    posterAvatar: PosterAvatar,
    qoute: "Part of the journey is the end.",
    desc: "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    mark: 8.3,
    type: "Movie",
    releaseDate: "2019-04-24",
    runTime: "181 min",
    genres: "Adventure,  Science Fiction, Action",
  },
  {
    id: 3,
    movieType: "Comedy",
    movieName: "How I Met Your Mother",
    poster: Poster,
    posterAvatar: PosterAvatar,
    qoute: "Part of the journey is the end.",
    desc: "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    mark: 8.3,
    type: "Movie",
    releaseDate: "2019-04-24",
    runTime: "181 min",
    genres: "Adventure,  Science Fiction, Action",
  },
  {
    id: 4,
    movieType: "Comedy",
    movieName: "Money Heist",
    poster: Poster,
    posterAvatar: PosterAvatar,
    qoute: "Part of the journey is the end.",
    desc: "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    mark: 8.3,
    type: "Movie",
    releaseDate: "2019-04-24",
    runTime: "181 min",
    genres: "Adventure,  Science Fiction, Action",
  },
  {
    id: 5,
    movieType: "Drama",
    movieName: "Friends",
    poster: Poster,
    posterAvatar: PosterAvatar,
    qoute: "Part of the journey is the end.",
    desc: "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    mark: 8.3,
    type: "Movie",
    releaseDate: "2019-04-24",
    runTime: "181 min",
    genres: "Adventure,  Science Fiction, Action",
  },
  {
    id: 6,
    movieType: "Comedy",
    movieName: "The Big Bang Theory",
    poster: Poster,
    posterAvatar: PosterAvatar,
    qoute: "Part of the journey is the end.",
    desc: "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    mark: 8.3,
    type: "Movie",
    releaseDate: "2019-04-24",
    runTime: "181 min",
    genres: "Adventure,  Science Fiction, Action",
  },
  {
    id: 7,
    movieType: "Comedy",
    movieName: "Two And a Half Men",
    poster: Poster,
    posterAvatar: PosterAvatar,
    qoute: "Part of the journey is the end.",
    desc: "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    mark: 8.3,
    type: "Movie",
    releaseDate: "2019-04-24",
    runTime: "181 min",
    genres: "Adventure,  Science Fiction, Action",
  }
];
