import Poster from "./assets/images/Poster.png";
import PosterAvatar from "./assets/images/PosterAvatar.png";

export const movies = [
  {
    id: 0,
    movieType: "Action",
    movieName: "Batman",
    poster: Poster,
    posterAvatar: PosterAvatar,
    qoute: "Part of the journey is the end.",
    desc: "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    mark: 8.3,
    type: "Movie",
    releaseDate: "2019-04-24",
    runTime: "181 min",
    genres: "Adventure,  Science Fiction, Action",
  },
  {
    id: 1,
    movieType: "Superman",
    movieName: "Avengers: Endgame",
    poster: Poster,
    posterAvatar: PosterAvatar,
    qoute: "Part of the journey is the end.",
    desc: "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    mark: 8.3,
    type: "Movie",
    releaseDate: "2019-04-24",
    runTime: "181 min",
    genres: "Adventure,  Science Fiction, Action",
  },
  {
    id: 2,
    movieType: "Trasformers",
    movieName: "Avengers: Endgame",
    poster: Poster,
    posterAvatar: PosterAvatar,
    qoute: "Part of the journey is the end.",
    desc: "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    mark: 8.3,
    type: "Movie",
    releaseDate: "2019-04-24",
    runTime: "181 min",
    genres: "Adventure,  Science Fiction, Action",
  },
  {
    id: 3,
    movieType: "Harry Potter",
    movieName: "Avengers: Endgame",
    poster: Poster,
    posterAvatar: PosterAvatar,
    qoute: "Part of the journey is the end.",
    desc: "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    mark: 8.3,
    type: "Movie",
    releaseDate: "2019-04-24",
    runTime: "181 min",
    genres: "Adventure,  Science Fiction, Action",
  },
  {
    id: 4,
    movieType: "Lord of the Rings",
    movieName: "Avengers: Endgame",
    poster: Poster,
    posterAvatar: PosterAvatar,
    qoute: "Part of the journey is the end.",
    desc: "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    mark: 8.3,
    type: "Movie",
    releaseDate: "2019-04-24",
    runTime: "181 min",
    genres: "Adventure,  Science Fiction, Action",
  },
  {
    id: 5,
    movieType: "Star Wars",
    movieName: "Avengers: Endgame",
    poster: Poster,
    posterAvatar: PosterAvatar,
    qoute: "Part of the journey is the end.",
    desc: "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    mark: 8.3,
    type: "Movie",
    releaseDate: "2019-04-24",
    runTime: "181 min",
    genres: "Adventure,  Science Fiction, Action",
  },
];
